### ISSUE TITLE
Incompatible with the Module: Module Sets - Dual Track GMing

### ISSUE THREAD

**Issue by Foxaramar** [ggagnon76/token-independence#27]
Incompatible with the Module: Module Sets - Dual Track GMing. The main switch that comes from that module disappears with token independence is active.

**Comment by ggagnon76** [comment]
I'll look into it.

**Comment by ggagnon76** [comment]
I figured this out.
The developer of the Module Sets module doesn't use a robust method of injecting their button into the sidebar. 
ANY module that manually refreshes the UI via:
`ui.sidebar.render(true)`
will rip out the toggle button of the HTML.
I will raise an issue with the Module Sets dev and close this issue.
